Feat/us10
hdkuzmahashmi/capstone-smartSaver pull request #32
Opened 2023-11-14 12:40 UTC by maryhbb

What's Implemented:

- Integrated react-datepicker and updated MongoDB to include date.
- Enhanced UI with date display on Expenses.
- Implemented versatile filtering: by Category, Amount Range, and Date Range.
- Added functionality to clear all selected filters.

2023-11-15 10:25 UTC, NikRoe requested changes
Hi there,

this looks really great already!

I left you a few comments.
The greatest news is: you can get rid of some of the states and both useEffects 🙌 

Keep it up 👏

2023-11-15 10:25 UTC, NikRoe commented on components/ExpenseList/index.jsx
> +  const [selectedToDateRange, setSelectedToDateRange] = useState("");
changing the names of these states to something like this might make it clearer:

```suggestion
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
```

you will need to rename the props accordingly, too

2023-11-15 10:25 UTC, NikRoe commented on components/RangeSlider/index.jsx
> +import { useEffect, useState } from "react";
```suggestion
import { useState } from "react";
```

2023-11-15 10:25 UTC, NikRoe commented on components/RangeSlider/index.jsx
> +  }, [selectedAmountRange]);
you won't need these lines of code, since you can use the `selectedAmountRange` state

2023-11-15 10:25 UTC, NikRoe commented on components/RangeSlider/index.jsx
> +          <SelectedRangeValue>{rangeValue} €</SelectedRangeValue>
```suggestion
            value={selectedAmountRange}
            onChange={(event) => {
              const newValue = parseInt(event.target.value);
              onAmountRangeChange(newValue);
            }}
          />
          <SelectedRangeValue>{selectedAmountRange} €</SelectedRangeValue>
```

2023-11-15 10:25 UTC, NikRoe commented on components/RangeSlider/index.jsx
> +            max="2000"
this is now hardcoded to 2000, but maybe there will at some point be an expense with a higher value.

You could consider making this dynamic and always have the value of the highest expense.

The code in your `ExpenseList` could look like this in case you want to try it out:

```js
const maxAmount = data.reduce((max, current) => {
    return current.amount > max.amount ? current : max;
  }, data[0]).amount;
```

2023-11-15 15:04 UTC, NikRoe requested changes
Hi there,

well done 👏 

I noticed a small thing regarding styled components I missed in my first review. 🙃

2023-11-15 15:04 UTC, NikRoe commented on components/DatePicker/index.jsx
> +      <CollapsiblePanelContainer collapsed={collapsedDate}>
```suggestion
      <CollapsiblePanelContainer $collapsed={collapsedDate}>
```

2023-11-15 15:04 UTC, NikRoe commented on components/FilterExpense/index.jsx
> +      <CollapsiblePanelContainer collapsed={collapsed}>
```suggestion
      <CollapsiblePanelContainer $collapsed={collapsed}>
```

2023-11-15 15:04 UTC, NikRoe commented on components/RangeSlider/index.jsx
> +      <CollapsiblePanelContainer collapsed={collapsedRange}>
```suggestion
      <CollapsiblePanelContainer $collapsed={collapsedRange}>
```

2023-11-15 15:04 UTC, NikRoe commented on design-system/StyledFilterExpense.js
> +  padding: ${(props) => (props.collapsed ? "0" : "10px")};
```suggestion
  max-height: ${(props) => (props.$collapsed ? "0" : "none")};
  padding: ${(props) => (props.$collapsed ? "0" : "10px")};
```

2023-11-16 07:13 UTC, NikRoe approved these changes
well done 👏

2023-11-16 08:36 UTC, maryhbb commented
> well done 👏

I appreciate your constructive feedback

2023-11-16 08:41 UTC, merged